name: haxball
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - git
  - pip
  - pip:
      - ipywidgets
      - openskill
      - optuna
      - optuna-dashboard
      - pettingzoo
      - PyDrive2
      - pyvirtualdisplay
      - stable-baselines3
      - supersuit
      - tensorboard
      - numpy==2.0.2
      - "setuptools<82"